var annotated_dup =
[
    [ "MatrixUtils", "namespaceMatrixUtils.html", [
      [ "Attributes", "namespaceMatrixUtils_1_1Attributes.html", [
        [ "ClassSelectorAttribute", "classMatrixUtils_1_1Attributes_1_1ClassSelectorAttribute.html", null ],
        [ "ReadOnlyAttribute", "classMatrixUtils_1_1Attributes_1_1ReadOnlyAttribute.html", null ],
        [ "RequiredFieldAttribute", "classMatrixUtils_1_1Attributes_1_1RequiredFieldAttribute.html", null ],
        [ "ShowIfAttribute", "classMatrixUtils_1_1Attributes_1_1ShowIfAttribute.html", null ]
      ] ],
      [ "AudioSystem", "namespaceMatrixUtils_1_1AudioSystem.html", [
        [ "SoundBuilder", "classMatrixUtils_1_1AudioSystem_1_1SoundBuilder.html", null ],
        [ "SoundData", "classMatrixUtils_1_1AudioSystem_1_1SoundData.html", null ],
        [ "SoundEmitter", "classMatrixUtils_1_1AudioSystem_1_1SoundEmitter.html", null ],
        [ "SoundManager", "classMatrixUtils_1_1AudioSystem_1_1SoundManager.html", null ]
      ] ],
      [ "DependencyInjection", "namespaceMatrixUtils_1_1DependencyInjection.html", [
        [ "IDependencyProvider", "interfaceMatrixUtils_1_1DependencyInjection_1_1IDependencyProvider.html", null ],
        [ "InjectAttribute", "classMatrixUtils_1_1DependencyInjection_1_1InjectAttribute.html", null ],
        [ "Injector", "classMatrixUtils_1_1DependencyInjection_1_1Injector.html", null ],
        [ "ProvideAttribute", "classMatrixUtils_1_1DependencyInjection_1_1ProvideAttribute.html", null ]
      ] ],
      [ "EventBus", "namespaceMatrixUtils_1_1EventBus.html", [
        [ "EventBinding", "classMatrixUtils_1_1EventBus_1_1EventBinding.html", null ],
        [ "IEvent", "interfaceMatrixUtils_1_1EventBus_1_1IEvent.html", null ],
        [ "IEventBinding", "interfaceMatrixUtils_1_1EventBus_1_1IEventBinding.html", null ]
      ] ],
      [ "GenericDatatypes", "namespaceMatrixUtils_1_1GenericDatatypes.html", [
        [ "CoroutineWithData", "classMatrixUtils_1_1GenericDatatypes_1_1CoroutineWithData.html", "classMatrixUtils_1_1GenericDatatypes_1_1CoroutineWithData" ],
        [ "Observer", "classMatrixUtils_1_1GenericDatatypes_1_1Observer.html", null ],
        [ "SerializableHashSet", "classMatrixUtils_1_1GenericDatatypes_1_1SerializableHashSet.html", "classMatrixUtils_1_1GenericDatatypes_1_1SerializableHashSet" ],
        [ "Singleton", "classMatrixUtils_1_1GenericDatatypes_1_1Singleton.html", "classMatrixUtils_1_1GenericDatatypes_1_1Singleton" ]
      ] ],
      [ "Logging", "namespaceMatrixUtils_1_1Logging.html", [
        [ "CustomLogger_SO", "classMatrixUtils_1_1Logging_1_1CustomLogger__SO.html", "classMatrixUtils_1_1Logging_1_1CustomLogger__SO" ]
      ] ],
      [ "ShaderHelpers", "namespaceMatrixUtils_1_1ShaderHelpers.html", [
        [ "NormalizedPositionAsUV0ZW", "classMatrixUtils_1_1ShaderHelpers_1_1NormalizedPositionAsUV0ZW.html", null ]
      ] ],
      [ "Timers", "namespaceMatrixUtils_1_1Timers.html", [
        [ "CountdownTimer", "classMatrixUtils_1_1Timers_1_1CountdownTimer.html", "classMatrixUtils_1_1Timers_1_1CountdownTimer" ],
        [ "FrequencyTimer", "classMatrixUtils_1_1Timers_1_1FrequencyTimer.html", null ],
        [ "IntervalTimer", "classMatrixUtils_1_1Timers_1_1IntervalTimer.html", "classMatrixUtils_1_1Timers_1_1IntervalTimer" ],
        [ "ITimer", "interfaceMatrixUtils_1_1Timers_1_1ITimer.html", null ],
        [ "StopwatchTimer", "classMatrixUtils_1_1Timers_1_1StopwatchTimer.html", null ],
        [ "Timer", "classMatrixUtils_1_1Timers_1_1Timer.html", null ]
      ] ],
      [ "VFXSystem", "namespaceMatrixUtils_1_1VFXSystem.html", [
        [ "VFXBuilder", "classMatrixUtils_1_1VFXSystem_1_1VFXBuilder.html", null ],
        [ "VFXData", "classMatrixUtils_1_1VFXSystem_1_1VFXData.html", null ],
        [ "VFXEmitter", "classMatrixUtils_1_1VFXSystem_1_1VFXEmitter.html", null ],
        [ "VFXManager", "classMatrixUtils_1_1VFXSystem_1_1VFXManager.html", "classMatrixUtils_1_1VFXSystem_1_1VFXManager" ]
      ] ],
      [ "ClampVector2", "classMatrixUtils_1_1ClampVector2.html", "classMatrixUtils_1_1ClampVector2" ],
      [ "OffsetVector2", "classMatrixUtils_1_1OffsetVector2.html", "classMatrixUtils_1_1OffsetVector2" ]
    ] ],
    [ "ShaderGraphExtension", "namespaceShaderGraphExtension.html", [
      [ "ShaderGraphStencilInjector", "classShaderGraphExtension_1_1ShaderGraphStencilInjector.html", null ],
      [ "StencilShaderGUI", "classShaderGraphExtension_1_1StencilShaderGUI.html", null ]
    ] ],
    [ "System", "namespaceSystem.html", [
      [ "Runtime", "namespaceSystem_1_1Runtime.html", [
        [ "CompilerServices", "namespaceSystem_1_1Runtime_1_1CompilerServices.html", [
          [ "IsExternalInit", "classSystem_1_1Runtime_1_1CompilerServices_1_1IsExternalInit.html", null ]
        ] ]
      ] ]
    ] ],
    [ "AnimationCurveVFXProperty", "classAnimationCurveVFXProperty.html", null ],
    [ "AspectRatioElement", "classAspectRatioElement.html", "classAspectRatioElement" ],
    [ "BoatCoordinate", "classBoatCoordinate.html", null ],
    [ "BoolVFXProperty", "classBoolVFXProperty.html", null ],
    [ "BottleInteractable", "classBottleInteractable.html", null ],
    [ "BuoyantBody", "classBuoyantBody.html", null ],
    [ "CalculateObjectVelocity", "classCalculateObjectVelocity.html", "classCalculateObjectVelocity" ],
    [ "CharacterSelectionDataHandler", "classCharacterSelectionDataHandler.html", null ],
    [ "CharacterSelectionSpawnManager", "classCharacterSelectionSpawnManager.html", null ],
    [ "CharacterSelectorButton", "classCharacterSelectorButton.html", null ],
    [ "CoalManager", "classCoalManager.html", "classCoalManager" ],
    [ "CoalUI", "classCoalUI.html", null ],
    [ "CollisionDamager", "classCollisionDamager.html", null ],
    [ "ColorVFXProperty", "classColorVFXProperty.html", null ],
    [ "CookFish", "classCookFish.html", "classCookFish" ],
    [ "CookingInteractable", "classCookingInteractable.html", "classCookingInteractable" ],
    [ "Crab", "classCrab.html", null ],
    [ "DataStorageBinding", "classDataStorageBinding.html", null ],
    [ "DelegateExtensions", "classDelegateExtensions.html", null ],
    [ "DriftEvent", "classDriftEvent.html", null ],
    [ "DropdownScroller", "classDropdownScroller.html", null ],
    [ "DynamicEventBinding", "classDynamicEventBinding.html", null ],
    [ "DynamicPersistentListener", "classDynamicPersistentListener.html", null ],
    [ "EndGame", "classEndGame.html", null ],
    [ "EngineSoundController", "classEngineSoundController.html", null ],
    [ "Fish", "classFish.html", null ],
    [ "FishingManager", "classFishingManager.html", "classFishingManager" ],
    [ "FishingMiniGame", "classFishingMiniGame.html", null ],
    [ "FishingMiniGameData", "classFishingMiniGameData.html", null ],
    [ "FishingUI", "classFishingUI.html", null ],
    [ "FloatVFXProperty", "classFloatVFXProperty.html", null ],
    [ "FoodClass", "classFoodClass.html", null ],
    [ "FuelWarning", "classFuelWarning.html", null ],
    [ "GameOverFirstSelected", "classGameOverFirstSelected.html", null ],
    [ "GradientVFXProperty", "classGradientVFXProperty.html", null ],
    [ "GramophoneInteractable", "classGramophoneInteractable.html", "classGramophoneInteractable" ],
    [ "GraphicsBufferVFXProperty", "classGraphicsBufferVFXProperty.html", null ],
    [ "HatchInteractable", "classHatchInteractable.html", "classHatchInteractable" ],
    [ "HeldObjectLocation", "classHeldObjectLocation.html", null ],
    [ "HelmInteractable", "classHelmInteractable.html", "classHelmInteractable" ],
    [ "HolePositionInfo", "structHolePositionInfo.html", null ],
    [ "HungerAndThirst", "classHungerAndThirst.html", null ],
    [ "HungerAndThirstVisualManager", "classHungerAndThirstVisualManager.html", null ],
    [ "ICharacterSelectionDataHandler", "interfaceICharacterSelectionDataHandler.html", null ],
    [ "IDamageable", "interfaceIDamageable.html", "interfaceIDamageable" ],
    [ "IDriftingEvent", "interfaceIDriftingEvent.html", null ],
    [ "IInjector", "interfaceIInjector.html", null ],
    [ "IInteractable", "interfaceIInteractable.html", "interfaceIInteractable" ],
    [ "IInteractor", "interfaceIInteractor.html", "interfaceIInteractor" ],
    [ "IMessageDisplay", "interfaceIMessageDisplay.html", "interfaceIMessageDisplay" ],
    [ "INotificationMessenger", "interfaceINotificationMessenger.html", null ],
    [ "InputData", "classInputData.html", null ],
    [ "InteractionSession", "classInteractionSession.html", "classInteractionSession" ],
    [ "InterfaceArgs", "structInterfaceArgs.html", null ],
    [ "InterfaceReference", "classInterfaceReference.html", null ],
    [ "IntVFXProperty", "classIntVFXProperty.html", null ],
    [ "IPersistentDataStorage", "interfaceIPersistentDataStorage.html", null ],
    [ "IPlayerControllable", "interfaceIPlayerControllable.html", "interfaceIPlayerControllable" ],
    [ "IPlayerController", "interfaceIPlayerController.html", "interfaceIPlayerController" ],
    [ "IProgressRepairProvider", "interfaceIProgressRepairProvider.html", null ],
    [ "IPromptDisplay", "interfaceIPromptDisplay.html", null ],
    [ "IPromptProvider", "interfaceIPromptProvider.html", null ],
    [ "ISceneTransitioner", "interfaceISceneTransitioner.html", null ],
    [ "ISpawner", "interfaceISpawner.html", null ],
    [ "ITransitionHider", "interfaceITransitionHider.html", null ],
    [ "IUsableItem", "interfaceIUsableItem.html", null ],
    [ "LightingManager", "classLightingManager.html", null ],
    [ "LightingPreset", "classLightingPreset.html", null ],
    [ "LiquidWobble", "classLiquidWobble.html", null ],
    [ "Matrix4x4VFXProperty", "classMatrix4x4VFXProperty.html", null ],
    [ "MeshVFXProperty", "classMeshVFXProperty.html", null ],
    [ "MovementTutorialStep", "classMovementTutorialStep.html", null ],
    [ "NeutralDriftingEvent", "classNeutralDriftingEvent.html", null ],
    [ "Optional", "structOptional.html", null ],
    [ "PassOutInteractable", "classPassOutInteractable.html", "classPassOutInteractable" ],
    [ "PersistentService", "classPersistentService.html", "classPersistentService" ],
    [ "PersistentSingleton", "classPersistentSingleton.html", "classPersistentSingleton" ],
    [ "PersistentSliderDataHandler", "classPersistentSliderDataHandler.html", null ],
    [ "PlayerController", "classPlayerController.html", "classPlayerController" ],
    [ "PlayerControllerDataStore", "classPlayerControllerDataStore.html", null ],
    [ "PlayerControlRouter", "classPlayerControlRouter.html", "classPlayerControlRouter" ],
    [ "PlayerInteractions", "classPlayerInteractions.html", null ],
    [ "PlayerInteractionState", "classPlayerInteractionState.html", null ],
    [ "PlayerInteractor", "classPlayerInteractor.html", "classPlayerInteractor" ],
    [ "PlayerLookRaycaster", "classPlayerLookRaycaster.html", null ],
    [ "PlayerMainMenuSpawner", "classPlayerMainMenuSpawner.html", null ],
    [ "PlayerMovement", "classPlayerMovement.html", null ],
    [ "PlayerPrefsDataStorage", "classPlayerPrefsDataStorage.html", null ],
    [ "PlayerSelectionCursor", "classPlayerSelectionCursor.html", null ],
    [ "PlayerSpawnManager", "classPlayerSpawnManager.html", null ],
    [ "PlayerTransitionHider", "classPlayerTransitionHider.html", null ],
    [ "PoliceBoatManager", "classPoliceBoatManager.html", null ],
    [ "PromptData", "classPromptData.html", "classPromptData" ],
    [ "PromptDisplay", "classPromptDisplay.html", null ],
    [ "QuitButton", "classQuitButton.html", null ],
    [ "RandomBag", "structRandomBag.html", null ],
    [ "RandomSoundPlayer", "classRandomSoundPlayer.html", null ],
    [ "RegulatorSingleton", "classRegulatorSingleton.html", "classRegulatorSingleton" ],
    [ "RepairPlate", "classRepairPlate.html", null ],
    [ "RequireInterfaceAttribute", "classRequireInterfaceAttribute.html", null ],
    [ "ResolutionDropdown", "classResolutionDropdown.html", null ],
    [ "Rope", "classRope.html", "classRope" ],
    [ "RoutineQueue", "classRoutineQueue.html", "classRoutineQueue" ],
    [ "SceneTransitionerProxy", "classSceneTransitionerProxy.html", null ],
    [ "SceneTransitionHandler", "classSceneTransitionHandler.html", null ],
    [ "ScriptableObjectEventListener", "classScriptableObjectEventListener.html", null ],
    [ "SerializableDictionary", "classSerializableDictionary.html", null ],
    [ "SerializableGrid", "classSerializableGrid.html", null ],
    [ "SerializableGuid", "structSerializableGuid.html", null ],
    [ "SerializableHashSet", "classSerializableHashSet.html", null ],
    [ "SerializableKeyValuePair", "structSerializableKeyValuePair.html", null ],
    [ "SerializableRegex", "classSerializableRegex.html", null ],
    [ "SerializableType", "classSerializableType.html", null ],
    [ "SerializedMethod", "classSerializedMethod.html", "classSerializedMethod" ],
    [ "ShipHealth", "classShipHealth.html", "classShipHealth" ],
    [ "ShipHole", "classShipHole.html", "classShipHole" ],
    [ "ShipHoleVisual", "classShipHoleVisual.html", null ],
    [ "ShipMovement", "classShipMovement.html", null ],
    [ "ShipRadar", "classShipRadar.html", null ],
    [ "SinkInteractable", "classSinkInteractable.html", "classSinkInteractable" ],
    [ "SkinnedMeshRendererVFXProperty", "classSkinnedMeshRendererVFXProperty.html", null ],
    [ "SO_CharacterSpecificData", "classSO__CharacterSpecificData.html", null ],
    [ "SO_CoalData", "classSO__CoalData.html", null ],
    [ "SO_CookableFoodData", "classSO__CookableFoodData.html", null ],
    [ "SO_UsableTerrain", "classSO__UsableTerrain.html", null ],
    [ "SO_WaterPathingTerrain", "classSO__WaterPathingTerrain.html", null ],
    [ "SoundSettings", "classSoundSettings.html", null ],
    [ "SplineMovement", "classSplineMovement.html", null ],
    [ "StorageInteractable", "classStorageInteractable.html", "classStorageInteractable" ],
    [ "TerrainCleanup", "classTerrainCleanup.html", null ],
    [ "TerrainEnvironmentSwaper", "classTerrainEnvironmentSwaper.html", null ],
    [ "TerrainOptions", "classTerrainOptions.html", null ],
    [ "TerrainSelector", "classTerrainSelector.html", null ],
    [ "TerrainSpawner", "classTerrainSpawner.html", null ],
    [ "tester", "classtester.html", null ],
    [ "TextureVFXProperty", "classTextureVFXProperty.html", null ],
    [ "TransitionReadyUpProxy", "classTransitionReadyUpProxy.html", null ],
    [ "TransitionWhenReadiedUp", "classTransitionWhenReadiedUp.html", null ],
    [ "TutorialContext", "structTutorialContext.html", null ],
    [ "TutorialMessageDisplay", "classTutorialMessageDisplay.html", "classTutorialMessageDisplay" ],
    [ "TutorialOrchestrator", "classTutorialOrchestrator.html", null ],
    [ "TutorialStep", "classTutorialStep.html", "classTutorialStep" ],
    [ "TypeFilterAttribute", "classTypeFilterAttribute.html", null ],
    [ "UIntVFXProperty", "classUIntVFXProperty.html", null ],
    [ "UnderbellyFollow", "classUnderbellyFollow.html", null ],
    [ "UnityEventFromInputAction", "classUnityEventFromInputAction.html", "classUnityEventFromInputAction" ],
    [ "Vector2VFXProperty", "classVector2VFXProperty.html", null ],
    [ "Vector3VFXProperty", "classVector3VFXProperty.html", null ],
    [ "Vector4VFXProperty", "classVector4VFXProperty.html", null ],
    [ "VFXProperty", "classVFXProperty.html", null ],
    [ "WarningIconMessageListener", "classWarningIconMessageListener.html", null ],
    [ "WarningIconMessenger", "classWarningIconMessenger.html", null ],
    [ "WaterController", "classWaterController.html", null ],
    [ "WaterFillController", "classWaterFillController.html", null ],
    [ "WaterValveInteractable", "classWaterValveInteractable.html", "classWaterValveInteractable" ],
    [ "WindowModeDropdown", "classWindowModeDropdown.html", null ]
];