var searchData=
[
  ['idamageable_0',['IDamageable',['../interfaceIDamageable.html',1,'']]],
  ['idependencyprovider_1',['IDependencyProvider',['../interfaceMatrixUtils_1_1DependencyInjection_1_1IDependencyProvider.html',1,'MatrixUtils::DependencyInjection']]],
  ['ievent_2',['IEvent',['../interfaceMatrixUtils_1_1EventBus_1_1IEvent.html',1,'MatrixUtils::EventBus']]],
  ['ieventbinding_3',['IEventBinding',['../interfaceMatrixUtils_1_1EventBus_1_1IEventBinding.html',1,'MatrixUtils::EventBus']]],
  ['iinjector_4',['IInjector',['../interfaceIInjector.html',1,'']]],
  ['iinteractable_5',['IInteractable',['../interfaceIInteractable.html',1,'']]],
  ['iinteractor_6',['IInteractor',['../interfaceIInteractor.html',1,'']]],
  ['initialize_7',['Initialize',['../classRoutineQueue.html#a55560ec7f20b8c1446e9d5a83f6d6cc7',1,'RoutineQueue']]],
  ['initializeservice_8',['InitializeService',['../classPersistentService.html#a458552f49c07410c28c7a6c145721bca',1,'PersistentService']]],
  ['initializesingleton_9',['InitializeSingleton',['../classMatrixUtils_1_1GenericDatatypes_1_1Singleton.html#a2267a74a71338992768b5ed17776c92f',1,'MatrixUtils::GenericDatatypes::Singleton']]],
  ['injectattribute_10',['InjectAttribute',['../classMatrixUtils_1_1DependencyInjection_1_1InjectAttribute.html',1,'MatrixUtils::DependencyInjection']]],
  ['injector_11',['Injector',['../classMatrixUtils_1_1DependencyInjection_1_1Injector.html',1,'MatrixUtils::DependencyInjection']]],
  ['inputdata_12',['InputData',['../classInputData.html',1,'']]],
  ['inputproperties_13',['InputProperties',['../classCalculateObjectVelocity_1_1InputProperties.html',1,'CalculateObjectVelocity']]],
  ['instance_14',['Instance',['../classMatrixUtils_1_1GenericDatatypes_1_1Singleton.html#a5574ce0f1a317e16a08c27a026f0c6fe',1,'MatrixUtils::GenericDatatypes::Singleton']]],
  ['interactionsession_15',['interactionsession',['../classInteractionSession.html',1,'InteractionSession'],['../classInteractionSession.html#adb8ae3d1e1810a3a4adfb5c25bcfd593',1,'InteractionSession.InteractionSession()']]],
  ['interfaceargs_16',['InterfaceArgs',['../structInterfaceArgs.html',1,'']]],
  ['interfacereference_17',['InterfaceReference',['../classInterfaceReference.html',1,'']]],
  ['interfacereference_3c_20iplayercontrollable_20_3e_18',['InterfaceReference&lt; IPlayerControllable &gt;',['../classInterfaceReference.html',1,'']]],
  ['interfacereference_3c_20iplayercontrollable_2c_20monobehaviour_20_3e_19',['InterfaceReference&lt; IPlayerControllable, MonoBehaviour &gt;',['../classInterfaceReference.html',1,'']]],
  ['interfacereference_3c_20ipromptdisplay_20_3e_20',['InterfaceReference&lt; IPromptDisplay &gt;',['../classInterfaceReference.html',1,'']]],
  ['interfacereference_3c_20tinterface_2c_20object_20_3e_21',['InterfaceReference&lt; TInterface, Object &gt;',['../classInterfaceReference.html',1,'']]],
  ['intervaltimer_22',['IntervalTimer',['../classMatrixUtils_1_1Timers_1_1IntervalTimer.html',1,'MatrixUtils::Timers']]],
  ['intvfxproperty_23',['IntVFXProperty',['../classIntVFXProperty.html',1,'']]],
  ['invoke_24',['invoke',['../classSerializedMethod.html#aa6f7a9066d0a654cd648d12814349fb8',1,'SerializedMethod.Invoke()'],['../classSerializedMethod.html#aa1a25506aa327971e0082d0a932864cc',1,'SerializedMethod.Invoke(object[] parameters)']]],
  ['iplayercontrollable_25',['IPlayerControllable',['../interfaceIPlayerControllable.html',1,'']]],
  ['iplayercontroller_26',['IPlayerController',['../interfaceIPlayerController.html',1,'']]],
  ['iplayerselection_27',['IPlayerSelection',['../interfaceIPlayerSelection.html',1,'']]],
  ['iplayerselectionhandler_28',['IPlayerSelectionHandler',['../interfaceIPlayerSelectionHandler.html',1,'']]],
  ['ipromptdisplay_29',['IPromptDisplay',['../interfaceIPromptDisplay.html',1,'']]],
  ['ipromptprovider_30',['IPromptProvider',['../interfaceIPromptProvider.html',1,'']]],
  ['isactive_31',['IsActive',['../classInteractionSession.html#a6d3fd4743e121a79aae444832d55cb3f',1,'InteractionSession']]],
  ['iscenetransitioner_32',['ISceneTransitioner',['../interfaceISceneTransitioner.html',1,'']]],
  ['isexternalinit_33',['IsExternalInit',['../classSystem_1_1Runtime_1_1CompilerServices_1_1IsExternalInit.html',1,'System::Runtime::CompilerServices']]],
  ['isinteracting_34',['isinteracting',['../interfaceIInteractor.html#add40295f5b68f9cc154d01b688f6dbe6',1,'IInteractor.IsInteracting()'],['../classPlayerInteractor.html#a571416a0e43c59ec34c67b063eb50d79',1,'PlayerInteractor.IsInteracting()']]],
  ['ispawner_35',['ISpawner',['../interfaceISpawner.html',1,'']]],
  ['itimer_36',['ITimer',['../interfaceMatrixUtils_1_1Timers_1_1ITimer.html',1,'MatrixUtils::Timers']]],
  ['itransitionhider_37',['ITransitionHider',['../interfaceITransitionHider.html',1,'']]]
];
